package cl.servel.gasto.model;
// Generated 13-09-2018 17:23:15 by Hibernate Tools 5.2.11.Final

import java.util.Date;



/**
 * AdmAdministradorElectoral generated by hbm2java
 */
public class DetalleActaRecepcion implements java.io.Serializable {
	
	private Integer darId;
	private Integer actaRecepcionId;
	private Integer candidatoId;
	private Integer partidoId;
	private Date darCreated;
	
	
	public Integer getDarId() {
		return darId;
	}
	public void setDarId(Integer darId) {
		this.darId = darId;
	}
	public Integer getActaRecepcionId() {
		return actaRecepcionId;
	}
	public void setActaRecepcionId(Integer actaRecepcionId) {
		this.actaRecepcionId = actaRecepcionId;
	}
	public Integer getCandidatoId() {
		return candidatoId;
	}
	public void setCandidatoId(Integer candidatoId) {
		this.candidatoId = candidatoId;
	}
	public Integer getPartidoId() {
		return partidoId;
	}
	public void setPartidoId(Integer partidoId) {
		this.partidoId = partidoId;
	}
	public Date getDarCreated() {
		return darCreated;
	}
	public void setDarCreated(Date darCreated) {
		this.darCreated = darCreated;
	}
	
	
}


