package cl.servel.gasto.model;
// Generated 11-03-2019 11:20:33 by Hibernate Tools 5.2.11.Final


/**
 * DecDetalleCarga generated by hbm2java
 */
public class DetalleCarga implements java.io.Serializable {

	private Integer decId;
	private Integer resumenCarga;
	private String decDescripcion;
	public Integer getDecId() {
		return decId;
	}
	public void setDecId(Integer decId) {
		this.decId = decId;
	}
	public Integer getResumenCarga() {
		return resumenCarga;
	}
	public void setResumenCarga(Integer resumenCarga) {
		this.resumenCarga = resumenCarga;
	}
	public String getDecDescripcion() {
		return decDescripcion;
	}
	public void setDecDescripcion(String decDescripcion) {
		this.decDescripcion = decDescripcion;
	}


	
}
