package cl.servel.gasto.model;
// Generated 13-09-2018 17:23:15 by Hibernate Tools 5.2.11.Final

import java.util.Date;


/**
 * NivNivel generated by hbm2java
 */
public class Nivel implements java.io.Serializable {
	
	private Integer nivId;
	private Integer idEveEventoEleccionario;
	private String tpoNivel;
	private String nivDescripcion;
	private Integer nivOrden;
	private String codigoOrigen;
	private Date nivCreated;
	private Boolean nivEliminado;
	private Date nivModified;
	public Integer getNivId() {
		return nivId;
	}
	public void setNivId(Integer nivId) {
		this.nivId = nivId;
	}
	public Integer getIdEveEventoEleccionario() {
		return idEveEventoEleccionario;
	}
	public void setIdEveEventoEleccionario(Integer idEveEventoEleccionario) {
		this.idEveEventoEleccionario = idEveEventoEleccionario;
	}
	public String getTpoNivel() {
		return tpoNivel;
	}
	public void setTpoNivel(String tpoNivel) {
		this.tpoNivel = tpoNivel;
	}
	public String getNivDescripcion() {
		return nivDescripcion;
	}
	public void setNivDescripcion(String nivDescripcion) {
		this.nivDescripcion = nivDescripcion;
	}
	public Integer getNivOrden() {
		return nivOrden;
	}
	public void setNivOrden(Integer nivOrden) {
		this.nivOrden = nivOrden;
	}
	public String getCodigoOrigen() {
		return codigoOrigen;
	}
	public void setCodigoOrigen(String codigoOrigen) {
		this.codigoOrigen = codigoOrigen;
	}
	public Date getNivCreated() {
		return nivCreated;
	}
	public void setNivCreated(Date nivCreated) {
		this.nivCreated = nivCreated;
	}
	public Boolean getNivEliminado() {
		return nivEliminado;
	}
	public void setNivEliminado(Boolean nivEliminado) {
		this.nivEliminado = nivEliminado;
	}
	public Date getNivModified() {
		return nivModified;
	}
	public void setNivModified(Date nivModified) {
		this.nivModified = nivModified;
	}
	
	
}
