package cl.servel.gasto.model;
// Generated 20-09-2018 12:02:44 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PamParametro generated by hbm2java
 */
public class PamParametro implements java.io.Serializable {

	private int id;
	
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String nombre;
	private Boolean isEliminado;
	private String valor;
	private Boolean parametroSistema;
	private Integer pamEveId;


	private Set relacionConfiguracionParametros = new HashSet(0);

	public PamParametro() {
	}

	public PamParametro(int id) {
		this.id = id;
	}

	
	public PamParametro(int id, Date fechaCreacion, Date fechaModificacion, String nombre, Boolean isEliminado,
			String valor, Boolean parametroSistema, Set relacionConfiguracionParametros) {

		this.id = id;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.nombre = nombre;
		this.isEliminado = isEliminado;
		this.valor = valor;
		this.parametroSistema = parametroSistema;
		this.relacionConfiguracionParametros = relacionConfiguracionParametros;
	}

	
	


	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getFechaCreacion() {
		return fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModificacion() {
		return fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Boolean getIsEliminado() {
		return isEliminado;
	}

	public void setIsEliminado(Boolean isEliminado) {
		this.isEliminado = isEliminado;
	}
	
	public String getValor() {
		return valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	public Boolean getParametroSistema() {
		return parametroSistema;
	}

	public void setParametroSistema(Boolean parametroSistema) {
		this.parametroSistema = parametroSistema;
	}
	
	public Integer getPamEveId() {
		return pamEveId;
	}

	public void setPamEveId(Integer pamEveId) {
		this.pamEveId = pamEveId;
	}

	public Set getRelacionConfiguracionParametros() {
		return this.relacionConfiguracionParametros;
	}

	public void setRelacionConfiguracionParametros(Set relacionConfiguracionParametros) {
		this.relacionConfiguracionParametros = relacionConfiguracionParametros;
	}

}
