package cl.servel.gasto.model;
// Generated 13-09-2018 17:23:15 by Hibernate Tools 5.2.11.Final

import java.util.Date;

/**
 * ParPartido generated by hbm2java
 */
public class Partido implements java.io.Serializable {

    /**
    * 
    */
    private static final long serialVersionUID = 1L;
    private Integer parId;
    private Integer idEleccion;
    private Integer idPacPacto;
    private Pacto pacto;
    private SubPacto subPacto;
    private Date parCreated;
    private String parCodigoOrigen;
    private Boolean parEliminado;
    private String parSigla;
    private String parNombre;
    private String parRut;
    private String parNombreAdm;
    private String parMail;
    private String parDireccion;
    private String parCiudad;
    private String parTelefonoCelu;
    private String parEstado;
    private Date parFechaDisolucion;
    private Date parFechaContitucion;
    private String parComuna;

 
	public Integer getParId() {
	return parId;
    }

    public String getParCiudad() {
		return parCiudad;
	}

	public void setParCiudad(String parCiudad) {
		this.parCiudad = parCiudad;
	}

	public void setParId(Integer parId) {
	this.parId = parId;
    }

    public Integer getIdPacPacto() {
	return idPacPacto;
    }

    public void setIdPacPacto(Integer idPacPacto) {
	this.idPacPacto = idPacPacto;
    }

    public String getParNombre() {
	return parNombre;
    }

    public void setParNombre(String parNombre) {
	this.parNombre = parNombre;
    }

    public String getParSigla() {
	return parSigla;
    }

    public void setParSigla(String parSigla) {
	this.parSigla = parSigla;
    }

    public Date getParCreated() {
	return parCreated;
    }

    public void setParCreated(Date parCreated) {
	this.parCreated = parCreated;
    }

    public String getParCodigoOrigen() {
	return parCodigoOrigen;
    }

    public void setParCodigoOrigen(String parCodigoOrigen) {
	this.parCodigoOrigen = parCodigoOrigen;
    }

    public Boolean getParEliminado() {
	return parEliminado;
    }

    public void setParEliminado(Boolean parEliminado) {
	this.parEliminado = parEliminado;
    }

    public Integer getIdEleccion() {
	return idEleccion;
    }

    public void setIdEleccion(Integer idEleccion) {
	this.idEleccion = idEleccion;
    }

    public Pacto getPacto() {
	return pacto;
    }

    public void setPacto(Pacto pacto) {
	this.pacto = pacto;
    }

    public SubPacto getSubPacto() {
	return subPacto;
    }

    public void setSubPacto(SubPacto subPacto) {
	this.subPacto = subPacto;
    }

    public String getParRut() {
	return parRut;
    }

    public void setParRut(String parRut) {
	this.parRut = parRut;
    }

    public String getParNombreAdm() {
	return parNombreAdm;
    }

    public void setParNombreAdm(String parNombreAdm) {
	this.parNombreAdm = parNombreAdm;
    }

    public String getParMail() {
	return parMail;
    }

    public void setParMail(String parMail) {
	this.parMail = parMail;
    }

    public String getParDireccion() {
	return parDireccion;
    }

    public void setParDireccion(String parDireccion) {
	this.parDireccion = parDireccion;
    }

    public String getParTelefonoCelu() {
	return parTelefonoCelu;
    }

    public void setParTelefonoCelu(String parTelefonoCelu) {
	this.parTelefonoCelu = parTelefonoCelu;
    }

    public String getParEstado() {
	return parEstado;
    }

    public void setParEstado(String parEstado) {
	this.parEstado = parEstado;
    }

    public Date getParFechaDisolucion() {
        return parFechaDisolucion;
    }

    public void setParFechaDisolucion(Date parFechaDisolucion) {
        this.parFechaDisolucion = parFechaDisolucion;
    }

	public Date getParFechaContitucion() {
		return parFechaContitucion;
	}

	public void setParFechaContitucion(Date parFechaContitucion) {
		this.parFechaContitucion = parFechaContitucion;
	}

	public String getParComuna() {
		return parComuna;
	}

	public void setParComuna(String parComuna) {
		this.parComuna = parComuna;
	}
}
