package cl.servel.gasto.model;
// Generated 13-09-2018 17:23:15 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;

/**
 * PerPerfil generated by hbm2java
 */
public class PerPerfil implements java.io.Serializable {

	private int perId;
	private String perNombrePerfil;
	private Set<RelPerfilFuncionalidad> relPerfilFuncionalidads = new HashSet<RelPerfilFuncionalidad>(0);
	private Set<RelUsuarioPerfil> relUsuarioPerfils = new HashSet<RelUsuarioPerfil>(0);

	public PerPerfil() {
	}

	public PerPerfil(int perId) {
		this.perId = perId;
	}

	public PerPerfil(int perId, String perNombrePerfil, Set<RelPerfilFuncionalidad> relPerfilFuncionalidads,
			Set<RelUsuarioPerfil> relUsuarioPerfils) {
		this.perId = perId;
		this.perNombrePerfil = perNombrePerfil;
		this.relPerfilFuncionalidads = relPerfilFuncionalidads;
		this.relUsuarioPerfils = relUsuarioPerfils;
	}

	public int getPerId() {
		return this.perId;
	}

	public void setPerId(int perId) {
		this.perId = perId;
	}

	public String getPerNombrePerfil() {
		return this.perNombrePerfil;
	}

	public void setPerNombrePerfil(String perNombrePerfil) {
		this.perNombrePerfil = perNombrePerfil;
	}

	public Set<RelPerfilFuncionalidad> getRelPerfilFuncionalidads() {
		return this.relPerfilFuncionalidads;
	}

	public void setRelPerfilFuncionalidads(Set<RelPerfilFuncionalidad> relPerfilFuncionalidads) {
		this.relPerfilFuncionalidads = relPerfilFuncionalidads;
	}

	public Set<RelUsuarioPerfil> getRelUsuarioPerfils() {
		return this.relUsuarioPerfils;
	}

	public void setRelUsuarioPerfils(Set<RelUsuarioPerfil> relUsuarioPerfils) {
		this.relUsuarioPerfils = relUsuarioPerfils;
	}

	@Override
	public String toString() {
		return "PerPerfil [perId=" + perId + ", perNombrePerfil=" + perNombrePerfil + ", relPerfilFuncionalidads="
				+ relPerfilFuncionalidads + ", relUsuarioPerfils=" + relUsuarioPerfils + "]";
	}
	
	

}
