package cl.servel.gasto.model;
// Generated 13-09-2018 17:23:15 by Hibernate Tools 5.2.11.Final

/**
 * RelacionConfiguracionParametro generated by hbm2java
 */
public class RelacionConfiguracionParametro implements java.io.Serializable {

	private RelacionConfiguracionParametroId id;
	private Integer idConfiguracion;
	private Parametros parametros;
	
	public RelacionConfiguracionParametroId getId() {
		return id;
	}
	public void setId(RelacionConfiguracionParametroId id) {
		this.id = id;
	}
	public Integer getIdConfiguracion() {
		return idConfiguracion;
	}
	public void setIdConfiguracion(Integer idConfiguracion) {
		this.idConfiguracion = idConfiguracion;
	}
	public Parametros getParametros() {
		return parametros;
	}
	public void setParametros(Parametros parametros) {
		this.parametros = parametros;
	}

	
	

}
