package cl.servel.gasto.model;
// Generated 13-09-2018 17:23:15 by Hibernate Tools 5.2.11.Final

import java.util.Date;



/**
 * RlcRelNivelId generated by hbm2java
 */
public class RelSubPactoPartido implements java.io.Serializable {

	private Integer rlcId;
	private Integer eleEleccion;
	private Integer idParPartido;
	private Integer idSpaPacto;
	
	
	
	public Integer getRlcId() {
		return rlcId;
	}
	public void setRlcId(Integer rlcId) {
		this.rlcId = rlcId;
	}
	public Integer getEleEleccion() {
		return eleEleccion;
	}
	public void setEleEleccion(Integer eleEleccion) {
		this.eleEleccion = eleEleccion;
	}
	public Integer getIdParPartido() {
		return idParPartido;
	}
	public void setIdParPartido(Integer idParPartido) {
		this.idParPartido = idParPartido;
	}
	public Integer getIdSpaPacto() {
		return idSpaPacto;
	}
	public void setIdSpaPacto(Integer idSpaPacto) {
		this.idSpaPacto = idSpaPacto;
	}
	
	
}
