package cl.servel.gasto.model;
// Generated 13-09-2018 17:23:15 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TpoEleccion generated by hbm2java
 */
public class TipoEleccion implements java.io.Serializable {

	private Integer tpoEleccionId;
	private String tpoEleNombre;
	private Boolean tpoEleEliminado;
	private Date created;
	private Date modified;
	private String tpoCodigoOrigen;
	private Integer tpoEleOrden;
	
	
	
	public String getTpoCodigoOrigen() {
		return tpoCodigoOrigen;
	}
	public void setTpoCodigoOrigen(String tpoCodigoOrigen) {
		this.tpoCodigoOrigen = tpoCodigoOrigen;
	}
	public Integer getTpoEleccionId() {
		return tpoEleccionId;
	}
	public void setTpoEleccionId(Integer tpoEleccionId) {
		this.tpoEleccionId = tpoEleccionId;
	}
	public String getTpoEleNombre() {
		return tpoEleNombre;
	}
	public void setTpoEleNombre(String tpoEleNombre) {
		this.tpoEleNombre = tpoEleNombre;
	}
	public Boolean getTpoEleEliminado() {
		return tpoEleEliminado;
	}
	public void setTpoEleEliminado(Boolean tpoEleEliminado) {
		this.tpoEleEliminado = tpoEleEliminado;
	}
	public Date getCreated() {
		return created;
	}
	public void setCreated(Date created) {
		this.created = created;
	}
	public Date getModified() {
		return modified;
	}
	public void setModified(Date modified) {
		this.modified = modified;
	}

	public Integer getTpoEleOrden() {
		return tpoEleOrden;
	}
	public void setTpoEleOrden(Integer tpoEleOrden) {
		this.tpoEleOrden = tpoEleOrden;
	}
	
}
