package cl.servel.gasto.model;
// Generated 13-09-2018 17:23:15 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TpoAdministrador generated by hbm2java
 */
public class TipoAdministrador implements java.io.Serializable {

	private Integer tpoAdmId;
	private String nombre;
	private Boolean tpoAdmEliminado;
	private Date fechaCreacion;
	private Date fechaModificacion;
	
	public TipoAdministrador() {
	}

	public TipoAdministrador(Integer tpoAdmId) {
		this.tpoAdmId = tpoAdmId;
	}

	public TipoAdministrador(Integer tpoAdmId, String nombre) {
		this.tpoAdmId = tpoAdmId;
		this.nombre = nombre;
		
	}

	public Integer getTpoAdmId() {
		return this.tpoAdmId;
	}

	public void setTpoAdmId(Integer tpoAdmId) {
		this.tpoAdmId = tpoAdmId;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Boolean getTpoAdmEliminado() {
		return tpoAdmEliminado;
	}

	public void setTpoAdmEliminado(Boolean tpoAdmEliminado) {
		this.tpoAdmEliminado = tpoAdmEliminado;
	}

	public Date getFechaCreacion() {
		return fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModificacion() {
		return fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Override
	public String toString() {
		return "TipoAdministrador [tpoAdmId=" + tpoAdmId + ", nombre=" + nombre + ", tpoAdmEliminado=" + tpoAdmEliminado
				+ ", fechaCreacion=" + fechaCreacion + ", fechaModificacion=" + fechaModificacion + "]";
	}	

}
