package cl.servel.gasto.model;
// Generated 19-09-2018 17:23:15 by Hibernate Tools 5.2.11.Final

import java.util.Date;

/**
 * TpoCandidato generated by hbm2java
 */
public class TipoCandidato implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Date fechaCreacion;
	private Boolean isEliminado;
	private Date fechaModificacion;

	public TipoCandidato() {
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaCreacion() {
		return fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Boolean getIsEliminado() {
		return isEliminado;
	}

	public void setIsEliminado(Boolean isEliminado) {
		this.isEliminado = isEliminado;
	}

	public Date getFechaModificacion() {
		return fechaModificacion;
	}

	public void setModified(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Override
	public String toString() {
		return "TpoCandidato [id=" + id + ", nombre=" + nombre + ", fechaCreacion=" + fechaCreacion + ", isEliminado="
				+ isEliminado + ", fechaModificacion=" + fechaModificacion + "]";
	}

}
