package cl.servel.gasto.model;
// Generated 13-09-2018 17:23:15 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TpoAdministrador generated by hbm2java
 */
public class TpoAdministrador implements java.io.Serializable {

	private int id;
	private String nombre;
	private Boolean isEliminado;
	private Date fechaCreacion;
	private Date fechaModificacion;
	
		public TpoAdministrador() {
	}

	public TpoAdministrador(int id) {
		this.id = id;
	}

	public TpoAdministrador(int id, String nombre) {
		this.id = id;
		this.nombre = nombre;
		
	}

	public int getTpoAdmId() {
		return this.id;
	}

	public void setTpoAdmId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Boolean getTpoAdmEliminado() {
		return isEliminado;
	}

	public void setTpoAdmEliminado(Boolean isEliminado) {
		this.isEliminado = isEliminado;
	}

	public Date getFechaCreacion() {
		return fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaModificacion() {
		return fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Override
	public String toString() {
		return "TpoAdministrador [id=" + id + ", nombre=" + nombre + ", isEliminado=" + isEliminado
				+ ", fechaCreacion=" + fechaCreacion + ", fechaModificacion=" + fechaModificacion + "]";
	}	

}
