package cl.servel.gasto.model;
// Generated 13-09-2018 17:23:15 by Hibernate Tools 5.2.11.Final

import java.util.Date;


/**
 * CanCandidato generated by hbm2java
 */
public class VotosCandidato implements java.io.Serializable {

	
	private Integer idTpoEleccion;
	private Integer votCantidadVotos;
	private Integer votCanRut;
	
	public Integer getIdTpoEleccion() {
		return idTpoEleccion;
	}
	public void setIdTpoEleccion(Integer idTpoEleccion) {
		this.idTpoEleccion = idTpoEleccion;
	}
	public Integer getVotCantidadVotos() {
		return votCantidadVotos;
	}
	public void setVotCantidadVotos(Integer votCantidadVotos) {
		this.votCantidadVotos = votCantidadVotos;
	}
	public Integer getVotCanRut() {
		return votCanRut;
	}
	public void setVotCanRut(Integer votCanRut) {
		this.votCanRut = votCanRut;
	}
	
	
	

}
