package cl.servel.gasto.enumerated;

public enum ColumnasEnum {
	REGION(1, "REGIÓN"), 
	CIRCUNSCRIPCION_PROVINCIAL(2, "CIRCUNSCRIPCIÓN PROVINCIAL"), 
	RUN(3, "RUN"), 
	NOMBRE(4, "NOMBRE"), 
	MONTO(5, "MONTO"), 
	CANDIDATO(6, "NOMBRE DEL CANDIDATO"),
	TERRITORIO(7, "TERRITORIO ELECTORAL"),
	TIPO(8, "TIPO"),
	ELECCION(9, "ELECCIÓN"),
	RUN_CANDIDATO(10, "RUN CANDIDATO"),
	DV(11, "DV"),	
	NOMBRE_CANDIDATO(12, "NOMBRE DEL CANDIDATO"),
	AFILIACION(13, "AFILIACIÓN"),
	NOMBRE_PARTIDO(14, "NOMBRE PARTIDO"),
	RUT_RUN_PROVEEDOR(15, "RUT O RUN DEL PROVEEDOR"),
	NOMBRE_PROVEEDOR(16, "NOMBRE PROVEEDOR"),
	FECHA_DOCUMENTO(17, "FECHA DOCUMENTO"),
	TIPO_DOCUMENTO(18, "TIPO DOCUMENTO"),
	DESCRIPCION_T_D(19, "DESCRIPCIÓN T/D"),
	TIPO_CUENTA(20, "TIPO CUENTA"),	
	DESCRIPCION_T_C(21, "DESCRIPCIÓN T/C"),
	NUMERO_DOCUMENTO(22, "NÚMERO DOCUMENTO"),
	GLOSA_DOCUMENTO(23, "GLOSA DOCUMENTO"),
	CATEGORIA(24, "CATEGORÍA"),
	TIPO_ELECCION(25, "TIPO DE ELECCIÓN"),
	RUT(26, "RUT"),
	APELLIDO_PATERNO_RAZON_SOCIAL(27, "APELLIDO PATERNO O RAZÓN SOCIAL"),
	APELLIDO_MATERNO(28, "APELLIDO MATERNO"),
	FOLIO(29, "FOLIO"),
	PAGO_REALIZADO(31, "PAGO REALIZADO"),
	CUENTA(32, "CUENTA"),
	BANCO(33, "BANCO"),
	FECHA(34, "FECHA"),
	ESTADO_ENVIO(35, "ESTADO ENVÍO"),
	MONTO_MULTA(36, "MONTO MULTA"),
	FECHA_ENVIO_MULTA(37, "FECHA ENVÍO MULTA"),
	ESTADO_MULTA(38, "ESTADO MULTA"),
	ETAPA(39, "ETAPA"),
	AGRUPACION(40, "AGRUPACIÓN"),
	USUARIO(41, "USUARIO"),
	FECHA_ASIGNACION(42, "FECHA ASIGNACIÓN"),
	FECHA_TERMINO(43, "FECHA TÉRMINO"),
	DV_PROVEEDOR(44, "DV DEL PROVEEDOR"),
	TIPO_MONEDA(45, "TIPO DE MONEDA"),
	MOVIMIENTO(46, "MOVIMIENTO"),
	RENDICION(47, "RENDICIÓN"),
	PAGINA(48, "PÁGINA"),
	LINEA(49, "LÍNEA"),
	DETALLE(50, "DETALLE"),
	DATO_MODIFICADO(51, "DATO MODIFICADO");

	private int id;
	private String descripcion;

	private ColumnasEnum(int id, String descripcion) {
		this.id = id;
		this.descripcion = descripcion;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
}