package cl.servel.gasto.enumerated;

public enum CuadraturasEnum {
	INGRESOS_EFECTIVOS_CANDIDATOS("150"),
	INGRESOS_EFECTIVOS_PARTIDOS("153"),
	GASTOS_EFECTIVOS_CANDIDATOS("261"),
	GASTOS_EFECTIVOS_PARTIDOS("264"),
	INGRESOS_VALORIZADOS_CANDIDATOS("151"),
	INGRESOS_VALORIZADOS_PARTIDOS("154"),
	GASTOS_VALORIZADOS_CANDIDATOS("262"),
	GASTOS_VALORIZADOS_PARTIDOS("265"),
	INGRESOS_TOTALES_CANDIDATOS("152"),
	INGRESOS_TOTALES_PARTIDOS("155"),
	GASTOS_TOTALES_CANDIDATOS("263"),
	GASTOS_TOTALES_PARTIDOS("266"),
	FINANCIAMIENTO_CANDIDATO_ARTICULO_15("361"),
	FINANCIAMIENTO_PARTIDO_ARTICULO_15("362"),
	APORTES_PROPIOS("111"),
	GASTOS_MENORES("260"),
	GASTOS_MENORES_INFORMADOS_CANDIDATO("165"),
	GASTOS_MENORES_INFORMADOS_PARTIDO("166"),
	APORTES_PROPIOS_INFORMADO_CANDIDATO("163"),
	APORTES_PROPIOS_INFORMADO_PARTIDO("164"),
	TOTAL_GASTO_INFORMADO_CANDIDATO("161"),
	TOTAL_GASTO_INFORMADO_PARTIDO("162"),
	REEMBOLSO_SOLICITADO_INSTITUCION_CANDIDATO("1401"),
	REEMBOLSO_SOLICITADO_INSTITUCION_PARTIDO("1402"),
	REEMBOLSO_AL_PARTIDO_CESION_DERECHO("1403"),
	REEMBOLSO_SOLICITADO_CANDIDATO("1404"),
	REEMBOLSO_SOLICITADO_PARTIDO("1405"),
	APORTE_PARTIDO_DINERO_DECLARADO_CANDIDATO("114"),
	APORTE_PROPIO_DECLARADO_CANDIDATO("1111"),
	APORTE_DECLARADO_POR_CANDIDATO("1113"),
	APORTE_DECLARADO_POR_PARTIDO("1112"),
	APORTE_DECLARADO_POR_CANDIDATO_PERSONAS_NATURALES_SRA("1114"),
	APORTE_DECLARADO_POR_PARTIDO_PERSONAS_NATURALES_SRA("1115"),
	APORTES_MENORES_SIN_PUBLICIDAD_CANDIDATO("1116"),
	APORTES_MENORES_SIN_PUBLICIDAD_PARTIDO("1117"),
	APORTE_PROPIO_EN_ESPECIES_CANDIDATO_INGRESOS("1118"),
	APORTE_PROPIO_EN_ESPECIES_CANDIDATO_GASTOS("1119"),
	APORTE_PROPIO_EN_ESPECIES_PARTIDO_INGRESOS("1124"),
	APORTE_PROPIO_EN_ESPECIES_PARTIDO_GASTOS("1125"),

	APORTE_TERCEROS_EN_ESPECIES_CANDIDATO_INGRESOS("1120"),
	APORTE_TERCEROS_EN_ESPECIES_CANDIDATO_GASTOS("1121"),
	APORTE_TERCEROS_EN_ESPECIES_PARTIDO_INGRESOS("1126"),
	APORTE_TERCEROS_EN_ESPECIES_PARTIDO_GASTOS("1127"),

	APORTE_PARTIDO_EN_ESPECIES_CANDIDATO_INGRESOS("1122"),
	APORTE_PARTIDO_EN_ESPECIES_CANDIDATO_GASTOS("1123");

	//	INGRESOS_EFECTIVOS("112"),
//	GASTOS_EFECTIVOS("261"),
//	FINANCIAMIENTO_CANDIDATO_ARTICULO_15("263"),
//	FINANCIAMIENTO_PARTIDO_ARTICULO_15("262"),
//	APORTES_PROPIOS("111"),
//	GASTOS_MENORES("260"),
//	TOTAL_GASTO_INFORMADO("264"),
//	REEMBOLSO_SOLICITADO_INSTITUCION("140"),
//	REEMBOLSO_AL_PARTIDO("141"),
//	REEMBOLSO_SOLICITADO_CANDIDATO("142"),
//	REEMBOLSO_SOLICITADO_PARTIDO("143"),
//	
//	APORTE_PROPIO_DECLARADO_CANDIDATO("1116"),
//	APORTE_DECLARADO_POR_CANDIDATO("1118"),
//	APORTE_DECLARADO_POR_CANDIDATO_PERSONAS_NATURALES_SRA("1119"),
//	APORTES_MENORES_SIN_PUBLICIDAD_CANDIDATO("1121"),
//	APORTE_PROPIO_EN_ESPECIES_CANDIDATO_INGRESOS("1111"),
//	APORTE_PROPIO_EN_ESPECIES_CANDIDATO_GASTOS("1112"),
//	APORTE_PROPIO_EN_ESPECIES_PARTIDO_INGRESOS("1114"),
//	APORTE_PROPIO_EN_ESPECIES_PARTIDO_GASTOS("1115");
	private CuadraturasEnum(String nombre) {
		this.nombre = nombre;
	}

	private String nombre;

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
}
