
package cl.servel.gasto.enumerated;

public enum FormulaEnum 
{

	FINANCIAMIENTO_INICIAL("FORMULA_FASE_1"),
	FORM_LG_PRESIDENTE_DEFINITIVA("FORMULA_LIMITE_PRESIDENTE_DEFINITIVA"),
	FORM_LG_PRESIDENTE_SEGUNDA_VOTACION("FORMULA_LIMITE_PRESIDENTE_2DA_VOTACION"),
	FORM_LG_SENADOR_GORE_1("FORMULA_LIMITE_SENADOR_GORE_TRAMO_1"),
	COND_LG_SENADOR_GORE_1("CONDICION_LIMITE_SENADOR_GORE_TRAMO_1"),
	FORM_LG_SENADOR_GORE_2("FORMULA_LIMITE_SENADOR_GORE_TRAMO_2"),
	COND_LG_SENADOR_GORE_2("CONDICION_LIMITE_SENADOR_GORE_TRAMO_2"),
	FORM_LG_SENADOR_GORE_3("FORMULA_LIMITE_SENADOR_GORE_TRAMO_3"),
	COND_LG_SENADOR_GORE_3("CONDICION_LIMITE_SENADOR_GORE_TRAMO_3"),
	FORM_LG_DIPUTADO("FORMULA_LIMITE_DIPUTADO"),
	FORM_LG_ALCALDE("FORMULA_LIMITE_ALCALDE"),
	COND_LG_ALCALDE_PERSO_1("CONDICION_MAX_APORTE_ALCALDE_POR_PERSONA_DEF"),
	FORM_LG_CONCEJAL("FORMULA_LIMITE_CONCEJAL"),
	COND_LG_CONCEJAL_PERSO_1("CONDICION_MAX_APORTE_CONCEJAL_PERSONA_DEFINITIVA"),
	FORM_LG_CORE_1("FORMULA_LIMITE_CORE_TRAMO_1"),
	COND_LG_CORE_1("CONDICION_LIMITE_CORE_TRAMO_1"),
	FORM_LG_CORE_2("FORMULA_LIMITE_CORE_TRAMO_2"),
	COND_LG_CORE_2("CONDICION_LIMITE_CORE_TRAMO_2"),
	FORM_LG_CORE_3("FORMULA_LIMITE_CORE_TRAMO_3"),
	COND_LG_CORE_3("CONDICION_LIMITE_CORE_TRAMO_3"),
	FORM_LG_PRESIDENTE_PRECANDIDATURA("FORMULA_LIMITE_PRESIDENTE_PRECANDIDATURA"),
	FORM_LG_SENADOR_GORE_SEGUNDA_VOTACION_1("FORMULA_LIMITE_SENADOR_GORE_2DA_VOTACION_TRAMO_1"),
	COND_LG_SENADOR_GORE_SEGUNDA_VOTACION_1("CONDICION_LIMITE_SENADOR_GORE_2DA_VOTACION_TRAMO_1"),
	FORM_LG_SENADOR_GORE_SEGUNDA_VOTACION_2("FORMULA_LIMITE_SENADOR_GORE_2DA_VOTACION_TRAMO_2"),
	COND_LG_SENADOR_GORE_SEGUNDA_VOTACION_2("CONDICION_LIMITE_SENADOR_GORE_2DA_VOTACION_TRAMO_2"),
	FORM_LG_SENADOR_GORE_SEGUNDA_VOTACION_3("FORMULA_LIMITE_SENADOR_GORE_2DA_VOTACION_TRAMO_3"),
	COND_LG_SENADOR_GORE_SEGUNDA_VOTACION_3("CONDICION_LIMITE_SENADOR_GORE_2DA_VOTACION_TRAMO_3");
	
	private String nombre;

	private FormulaEnum(String nombre) 
	{
		this.nombre = nombre;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) 
	{
		this.nombre = nombre;
	}
}
