package cl.servel.gasto.enumerated;

public enum InformeAuditoriaEnum {
	AUDIT_MODULO1("I. INDIVIDUALIZACIÓN DEL CANDIDATO Y ADMINISTRADOR ELECTORAL"),
	AUDIT_MODULO2("II. INGRESOS Y GASTOS ELECTORALES PRESENTADOS"),
	AUDIT_MODULO3("III. OFICIO DE OBSERVACIONES Y RESPUESTAS"),
	AUDIT_MODULO4("IV. AUDITORÍA DE OBSERVACIONES"),
	AUDIT_MODULO5("V. INGRESOS Y GASTOS ELECTORALES DESPUÉS DE LA AUDITORÍA"),
	AUDIT_MODULO6("VI. CUADRATURA DE LIMITES DE FINANCIAMIENTO Y GASTO ELECTORAL"),
	AUDIT_MODULO7("VII. DETERMINACIÓN REEMBOLSO"),
	AUDIT_MODULO8("VIII. OPINIÓN DEL AUDITOR"),
	AUDIT_MODULO9("IX. INTEGRANTES REVISIÓN"),
	AUDIT_MODULO10("X. AUTORIZACIÓN INFORME DE LA AUDITORÍA AUDITOR SENIOR"),
	AUDIT_MODULO11("XI. FIRMAS JEFATURA");
	
	private String titulo;
	public String getTitulo() {
		return titulo;
	}
	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}
	private InformeAuditoriaEnum(String titulo) {
		this.titulo=titulo;
		
	}
}
