package cl.servel.gasto.enumerated;

public enum NombreParametroEnum {
	SEQ_OFICIO_OBSERVACIONES("SEQ_OFICIO_OBSERVACION", "Numero oficio observaciones"),
	SEQ_INFORME_AUDITORIA("SEQ_INFORME_AUDITORIA", "Numero oficio auditoría"),
	SEQ_RESOLUCIONES("SEQ_RESOLUCIONES", "Numero oficio resoluciones"),
	/*TABLA_CESION_DERECHOS("TABLA_CESION_DERECHOS", "Tabla para cesión de derechos de reembolso"),
	TABLA_CREDITO_MANDATO("TABLA_CREDITO_MANDATO", "Tabla para crédito con mandatos"),
	TABLA_REEMBOLSO_SOLICITADO("TABLA_REEMBOLSO_SOLICITADO", "Tabla para reembolso solicitado"),*/
	SEQ_EXPEDIENTE("SEQ_EXPEDIENTE","Nro expediente impresion"),
	SEQ_FOLIO_NOMINA("SEQ_FOLIO_NOMINA", "Secuencia para el folio de nómina"),
	PAR_MUJER_CONSIDERANDO_1("PAR_MUJER_CONSIDERANDO-1",""),
	PAR_MUJER_CONSIDERANDO_TABLA_CANDIDATAS_PARTIDOS("PAR_MUJER_CONSIDERANDO_TABLA_CANDIDATAS_PARTIDOS",""),
	PAR_MUJER_CONSIDERANDO_2("PAR_MUJER_CONSIDERANDO-2",""),
	PAR_MUJER_CONSIDERANDO_3("PAR_MUJER_CONSIDERANDO-3",""),
	PAR_MUJER_CONSIDERANDO_4("PAR_MUJER_CONSIDERANDO-4",""),
	PAR_MUJER_CONSIDERANDO_5("PAR_MUJER_CONSIDERANDO-5",""),
	PAR_MUJER_RESUELVO_1("PAR_MUJER_RESUELVO-1",""),
	PAR_MUJER_RESUELVO_TABLA_CANDIDATAS("PAR_MUJER_RESUELVO_TABLA_CANDIDATAS",""),
	PAR_MUJER_RESUELVO_2("PAR_MUJER_RESUELVO-2",""),
	PAR_REMANENTE_VISTO_1("PAR_REMANENTE_VISTO-1",""),
	PAR_REMANENTE_VISTO_2("PAR_REMANENTE_VISTO-2",""),
	PAR_REMANENTE_VISTO_3("PAR_REMANENTE_VISTO-3",""),
	PAR_REMANENTE_CONSIDERANDO_1("PAR_REMANENTE_CONSIDERANDO-1",""),
	PAR_REMANENTE_CONSIDERANDO_2("PAR_REMANENTE_CONSIDERANDO-2",""),
	PAR_REMANENTE_CONSIDERANDO_3("PAR_REMANENTE_CONSIDERANDO-3",""),
	PAR_REMANENTE_CONSIDERANDO_4("PAR_REMANENTE_CONSIDERANDO-4",""),
	PAR_REMANENTE_CONSIDERANDO_TABLA_REMANENTES_GASTO("PAR_REMANENTE_CONSIDERANDO_TABLA_REMANENTES_GASTO",""),
	PAR_REMANENTE_CONSIDERANDO_5("PAR_REMANENTE_CONSIDERANDO-5",""),
	PAR_REMANENTE_CONSIDERANDO_TABLA_REMANENTES_CAND("PAR_REMANENTE_CONSIDERANDO_TABLA_REMANENTES_CAND",""),
	PAR_REMANENTE_RESUELVO_1("PAR_REMANENTE_RESUELVO-1",""),
	PAR_REMANENTE_RESUELVO_2("PAR_REMANENTE_RESUELVO-2",""),
	PAR_REMANENTE_RESUELVO_3("PAR_REMANENTE_RESUELVO-3",""),
	PAR_MUJER_DIST_1("PAR_MUJER_DIST-1",""),
	PAR_MUJER_DIST_2("PAR_MUJER_DIST-2",""),
	PAR_MUJER_DIST_3("PAR_MUJER_DIST-3",""),
	PAR_REMANENTE_DIST_1("PAR_REMANENTE_DIST-1",""),
	PAR_REMANENTE_DIST_2("PAR_REMANENTE_DIST-2",""),
	PAR_REMANENTE_DIST_3("PAR_REMANENTE_DIST-3",""),
	PAR_REMANENTE_DIST_4("PAR_REMANENTE_DIST-4","");
	
	private String codigo;
	private String descripcion;

	private NombreParametroEnum(String codigo, String descripcion) {
		this.codigo = codigo;
		this.descripcion = descripcion;
	}
	public String getCodigo() {
		return codigo;
	}
	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}
	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
}
