package cl.servel.gasto.enumerated;

public enum TipoDocumentoExternoEnum {

	RESPUESTAS_OBSERVACIONES("RESPUESTAS_OBSERVACIONES"),
	DECLARACION_CANDIDATURA("DECLARACION_CANDIDATURA"),
	DESIGNACION_ACEPTACION_ADM("DESIGNACION_ACEPTACION_ADM"),
	DECLARACION_JURADA("DECLARACION_JURADA"),
	AUTORIZACION_APERTURA_CTA("AUTORIZACION_APERTURA_CTA"),
	F87("F87"),
	F88("F88"),
	NOTIFICACION_CORREO_ELECTRONICO_OBS("NOTIFICACION_CORREO_ELECTRONICO_OBS"),
	CERTIFICACION_NOTIFICACION_OBS("CERTIFICACION_NOTIFICACION_OBS"),
	NOTIFICACION_RESOL("NOTIFICACION_RESOL"),
	CERTIFICACION_NOTIFICACION_RESOL("CERTIFICACION_NOTIFICACION_RESOL"),
	RECURSO_RECLAMACION("RECURSO_RECLAMACION"),
	RECURSO_REPOSICION("RECURSO_REPOSICION"),
	RECURSO_REPOSICION_SUBSIDIO("RECURSO_REPOSICION_SUBSIDIO"),
	RESOLUCION_ELEVASE("RESOLUCION_ELEVASE"),
	OFICIO_ENVIO_TRICEL("OFICIO_ENVIO_TRICEL"),
	INGRESO_RECURSOS("ingresoRecursos");
	
	private TipoDocumentoExternoEnum(String codigo) {
		this.codigo = codigo;
	}

	private String codigo;

	public String getCodigo() {
		return codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}
}
