package cl.servel.gasto.model;
// Generated 13-09-2018 17:23:15 by Hibernate Tools 5.2.11.Final

import java.util.Date;

/**
 * AdmAdministradorElectoral generated by hbm2java
 */
public class ActaRecepcion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer acrId;
	private Integer eventoEleccionarioId;
	private Integer tpoEventoId;
	private Date acrFechaRecepcion;
	private String rutResponsable;
	private Character dvResponsable;
	private String nombreResponsable;
	private String acrObservaciones;
	private Date acrCreated;
	private String acrEstado;
	private String acrGlosaSuperior;
	private String acrGlosaInferior;
	private String acrCorreo;

	public String getRutResponsable() {
		return rutResponsable;
	}

	public void setRutResponsable(String rutResponsable) {
		this.rutResponsable = rutResponsable;
	}

	public Character getDvResponsable() {
		return dvResponsable;
	}

	public void setDvResponsable(Character dvResponsable) {
		this.dvResponsable = dvResponsable;
	}

	public String getNombreResponsable() {
		return nombreResponsable;
	}

	public void setNombreResponsable(String nombreResponsable) {
		this.nombreResponsable = nombreResponsable;
	}

	public Integer getEventoEleccionarioId() {
		return eventoEleccionarioId;
	}

	public void setEventoEleccionarioId(Integer eventoEleccionarioId) {
		this.eventoEleccionarioId = eventoEleccionarioId;
	}
	
	public Integer getTpoEventoId() {
		return tpoEventoId;
	}

	public void setTpoEventoId(Integer tpoEventoId) {
		this.tpoEventoId = tpoEventoId;
	}

	public Integer getAcrId() {
		return acrId;
	}

	public void setAcrId(Integer acrId) {
		this.acrId = acrId;
	}

	public Date getAcrFechaRecepcion() {
		return acrFechaRecepcion;
	}

	public void setAcrFechaRecepcion(Date acrFechaRecepcion) {
		this.acrFechaRecepcion = acrFechaRecepcion;
	}

	public String getAcrObservaciones() {
		return acrObservaciones;
	}

	public void setAcrObservaciones(String acrObservaciones) {
		this.acrObservaciones = acrObservaciones;
	}

	public Date getAcrCreated() {
		return acrCreated;
	}

	public void setAcrCreated(Date acrCreated) {
		this.acrCreated = acrCreated;
	}

	public String getAcrEstado() {
		return acrEstado;
	}

	public void setAcrEstado(String acrEstado) {
		this.acrEstado = acrEstado;
	}

	public String getAcrGlosaSuperior() {
		return acrGlosaSuperior;
	}

	public void setAcrGlosaSuperior(String acrGlosaSuperior) {
		this.acrGlosaSuperior = acrGlosaSuperior;
	}

	public String getAcrGlosaInferior() {
		return acrGlosaInferior;
	}

	public void setAcrGlosaInferior(String acrGlosaInferior) {
		this.acrGlosaInferior = acrGlosaInferior;
	}

	public String getAcrCorreo() {
		return acrCorreo;
	}

	public void setAcrCorreo(String acrCorreo) {
		this.acrCorreo = acrCorreo;
	}		
	
}
