package cl.servel.gasto.model;
// Generated 13-09-2018 17:23:15 by Hibernate Tools 5.2.11.Final

import java.util.Date;

import org.apache.commons.lang3.StringUtils;

/**
 * AdmAdministradorElectoral generated by hbm2java
 */
public class AdmAdministradorElectoral implements java.io.Serializable {

	private Integer admId;
	private Integer parPartidoId;
	private Integer tpoAdministradorId;
	private Integer idEventoEleccionario;
	private String admNombre;
	private String admAppPaterno;
	private String admAppMaterno;
	private String admRut;
	private String admRutDv;
	private String admMail;
	private String admTelefonoFijo;
	private String admTelefonoCelu;
	private String admCtaBanco;
	private Date admCreated;
	private String admEstado;
	private Date admModified;
	private String admCodigoOrigen;
	private Boolean admEliminado;
	private String admDireccion;
	private String admComuna;

	public AdmAdministradorElectoral() {
	}

	public AdmAdministradorElectoral(int admId, Integer parPartidoId, Integer tpoAdministradorId,Integer idEventoEleccionario) {
		this.admId = admId;
		this.parPartidoId = parPartidoId;
		this.tpoAdministradorId = tpoAdministradorId;
		this.idEventoEleccionario=idEventoEleccionario;
	}

	public AdmAdministradorElectoral(int admId, Integer parPartidoId, Integer tpoAdministradorId,Integer idEventoEleccionario,
			String admNombre, String admAppPaterno, String admAppMaterno, String admRut, String admRutDv,
			String admMail, String admTelefonoFijo, String admTelefonoCelu, String admCtaBanco, Date admCreated,
			String admEstado, Date admModified, String admCodigoOrigen) {
		this.admId = admId;
		this.parPartidoId = parPartidoId;
		this.tpoAdministradorId = tpoAdministradorId;
		this.idEventoEleccionario=idEventoEleccionario;
		this.admNombre = admNombre;
		this.admAppPaterno = admAppPaterno;
		this.admAppMaterno = admAppMaterno;
		this.admRut = admRut;
		this.admRutDv = admRutDv;
		this.admMail = admMail;
		this.admTelefonoFijo = admTelefonoFijo;
		this.admTelefonoCelu = admTelefonoCelu;
		this.admCtaBanco = admCtaBanco;
		this.admCreated = admCreated;
		this.admEstado = admEstado;
		this.admModified = admModified;
		this.admCodigoOrigen = admCodigoOrigen;
	}

	public Integer getAdmId() {
		return this.admId;
	}
	/*
	public void setAdmId(int admId) {
		this.admId = admId;
	}*/

	

	public Integer getIdEventoEleccionario() {
		return idEventoEleccionario;
	}

	public void setIdEventoEleccionario(Integer idEventoEleccionario) {
		this.idEventoEleccionario = idEventoEleccionario;
	}

	public String getAdmNombre() {
		return this.admNombre;
	}

	public void setAdmNombre(String admNombre) {
		this.admNombre = admNombre;
	}

	public String getAdmAppPaterno() {
		return this.admAppPaterno;
	}

	public void setAdmAppPaterno(String admAppPaterno) {
		this.admAppPaterno = admAppPaterno;
	}

	public String getAdmAppMaterno() {
		return this.admAppMaterno;
	}

	public void setAdmAppMaterno(String admAppMaterno) {
		this.admAppMaterno = admAppMaterno;
	}

	public String getAdmRut() {
		return this.admRut;
	}

	public void setAdmRut(String admRut) {
		this.admRut = admRut;
	}

	public String getAdmRutDv() {
		return this.admRutDv;
	}

	public void setAdmRutDv(String admRutDv) {
		this.admRutDv = admRutDv;
	}

	public String getAdmMail() {
		return this.admMail;
	}

	public void setAdmMail(String admMail) {
		this.admMail = admMail;
	}

	public String getAdmTelefonoFijo() {
		return this.admTelefonoFijo;
	}

	public void setAdmTelefonoFijo(String admTelefonoFijo) {
		this.admTelefonoFijo = admTelefonoFijo;
	}

	public String getAdmTelefonoCelu() {
		return this.admTelefonoCelu;
	}

	public void setAdmTelefonoCelu(String admTelefonoCelu) {
		this.admTelefonoCelu = admTelefonoCelu;
	}

	public String getAdmCtaBanco() {
		return this.admCtaBanco;
	}

	public void setAdmCtaBanco(String admCtaBanco) {
		this.admCtaBanco = admCtaBanco;
	}

	public Date getAdmCreated() {
		return this.admCreated;
	}

	public void setAdmCreated(Date admCreated) {
		this.admCreated = admCreated;
	}

	public String getAdmEstado() {
		return this.admEstado;
	}

	public void setAdmEstado(String admEstado) {
		this.admEstado = admEstado;
	}



	public Integer getParPartidoId() {
		return parPartidoId;
	}

	public void setParPartidoId(Integer parPartidoId) {
		this.parPartidoId = parPartidoId;
	}

	public Integer getTpoAdministradorId() {
		return tpoAdministradorId;
	}

	public void setTpoAdministradorId(Integer tpoAdministradorId) {
		this.tpoAdministradorId = tpoAdministradorId;
	}

	public Date getAdmModified() {
		return admModified;
	}

	public void setAdmModified(Date admModified) {
		this.admModified = admModified;
	}


	public void setAdmId(Integer admId) {
		this.admId = admId;
	}

	public String getAdmCodigoOrigen() {
		return this.admCodigoOrigen;
	}

	public void setAdmCodigoOrigen(String admCodigoOrigen) {
		this.admCodigoOrigen = admCodigoOrigen;
	}



	public Boolean getAdmEliminado() {
		return admEliminado;
	}

	public void setAdmEliminado(Boolean admEliminado) {
		this.admEliminado = admEliminado;
	}
	
	public String getAdmDireccion() {
		return admDireccion;
	}

	public void setAdmDireccion(String admDireccion) {
		this.admDireccion = admDireccion;
	}

	public String getAdmComuna() {
		return admComuna;
	}

	public void setAdmComuna(String admComuna) {
		this.admComuna = admComuna;
	}
	
	public String getNombreCompleto() {
		StringBuilder nombreCompleto = new StringBuilder();
		
		nombreCompleto.append(getAdmNombre()).append(" ").append(getAdmAppPaterno()).append(" ").append(getAdmAppMaterno());
		
		return nombreCompleto.toString();
	}

	@Override
	public String toString() {
		return "AdmAdministradorElectoral [admId=" + admId + ", parPartidoId=" + parPartidoId + ", tpoAdministradorId="
				+ tpoAdministradorId + ", idEventoEleccionario=" + idEventoEleccionario + ", admNombre=" + admNombre
				+ ", admAppPaterno=" + admAppPaterno + ", admAppMaterno=" + admAppMaterno + ", admRut=" + admRut
				+ ", admRutDv=" + admRutDv + ", admMail=" + admMail + ", admTelefonoFijo=" + admTelefonoFijo
				+ ", admTelefonoCelu=" + admTelefonoCelu + ", admCtaBanco=" + admCtaBanco + ", admCreated=" + admCreated
				+ ", admEstado=" + admEstado + ", admModified=" + admModified + ", admCodigoOrigen=" + admCodigoOrigen
				+ ", admEliminado=" + admEliminado + "]";
	}
}
