package cl.servel.gasto.model;
// Generated 13-09-2018 17:23:15 by Hibernate Tools 5.2.11.Final

import java.util.Date;

import org.apache.commons.lang3.StringUtils;


/**
 * CanCandidato generated by hbm2java
 */
public class Candidato implements java.io.Serializable {

	
	private Integer canId;
	
	private Integer idEveEventoEleccionario;
	
	private Integer idPacPacto;
	private String desPacPacto;
	
	private Integer idParPartido;
	private String desParPartido;
	
	private Integer idSelSubEleccion;
	
	private Integer idSpaPacto;
	private String desSpaPacto;
	
	private Integer idTpoCandidato;

	private String canNombres;
	private String canAppPaterno;
	private String canAppMaterno;
	private String canSexo;
	private String canMail;
	private String canDirPostal;
	private String canDireccion;
	private String canComuna;
	private String canFechaNacimiento;
	private String canTelefonoFijo;
	private String canTelefonoCelu;
	private Integer canNumeroEnVoto;
	private Integer canCantidadVotos;
	private Integer canRut;
	private Character canRutDv;
	private String canEstado;
	private String canEstadoCandidatura;
	private Boolean canEliminado;
	private Boolean canHabilitado;
	private Date canCreated;
	private Date canModified;
	private String canCodigoOrigen;
	private Integer tpoCanId;
	private String desTpoCan;
	private Boolean canElecto;
	
	public Integer getCanId() {
		return canId;
	}
	public void setCanId(Integer canId) {
		this.canId = canId;
	}
	public Integer getIdEveEventoEleccionario() {
		return idEveEventoEleccionario;
	}
	public void setIdEveEventoEleccionario(Integer idEveEventoEleccionario) {
		this.idEveEventoEleccionario = idEveEventoEleccionario;
	}
	public Integer getIdPacPacto() {
		return idPacPacto;
	}
	public void setIdPacPacto(Integer idPacPacto) {
		this.idPacPacto = idPacPacto;
	}
	public Integer getIdParPartido() {
		return idParPartido;
	}
	public void setIdParPartido(Integer idParPartido) {
		this.idParPartido = idParPartido;
	}
	public Integer getIdSelSubEleccion() {
		return idSelSubEleccion;
	}
	public void setIdSelSubEleccion(Integer idSelSubEleccion) {
		this.idSelSubEleccion = idSelSubEleccion;
	}
	public Integer getIdSpaPacto() {
		return idSpaPacto;
	}
	public void setIdSpaPacto(Integer idSpaPacto) {
		this.idSpaPacto = idSpaPacto;
	}
	public Integer getIdTpoCandidato() {
		return idTpoCandidato;
	}
	public void setIdTpoCandidato(Integer idTpoCandidato) {
		this.idTpoCandidato = idTpoCandidato;
	}
	public String getCanNombres() {
		return canNombres;
	}
	public void setCanNombres(String canNombres) {
		this.canNombres = canNombres;
	}
	public String getCanAppPaterno() {
		return canAppPaterno;
	}
	public void setCanAppPaterno(String canAppPaterno) {
		this.canAppPaterno = canAppPaterno;
	}
	public String getCanAppMaterno() {
		return canAppMaterno;
	}
	public void setCanAppMaterno(String canAppMaterno) {
		this.canAppMaterno = canAppMaterno;
	}
	public String getCanSexo() {
		return canSexo;
	}
	public void setCanSexo(String canSexo) {
		this.canSexo = canSexo;
	}
	public String getCanMail() {
		return canMail;
	}
	public void setCanMail(String canMail) {
		this.canMail = canMail;
	}
	public String getCanDirPostal() {
		return canDirPostal;
	}
	public void setCanDirPostal(String canDirPostal) {
		this.canDirPostal = canDirPostal;
	}
	public String getCanDireccion() {
		return canDireccion;
	}
	public void setCanDireccion(String canDireccion) {
		this.canDireccion = canDireccion;
	}
	public String getCanComuna() {
		return canComuna;
	}
	public void setCanComuna(String canComuna) {
		this.canComuna = canComuna;
	}
	public String getCanFechaNacimiento() {
		return canFechaNacimiento;
	}
	public void setCanFechaNacimiento(String canFechaNacimiento) {
		this.canFechaNacimiento = canFechaNacimiento;
	}
	public String getCanTelefonoFijo() {
		return canTelefonoFijo;
	}
	public void setCanTelefonoFijo(String canTelefonoFijo) {
		this.canTelefonoFijo = canTelefonoFijo;
	}
	public String getCanTelefonoCelu() {
		return canTelefonoCelu;
	}
	public void setCanTelefonoCelu(String canTelefonoCelu) {
		this.canTelefonoCelu = canTelefonoCelu;
	}
	public Integer getCanNumeroEnVoto() {
		return canNumeroEnVoto;
	}
	public void setCanNumeroEnVoto(Integer canNumeroEnVoto) {
		this.canNumeroEnVoto = canNumeroEnVoto;
	}
	public Integer getCanRut() {
		return canRut;
	}
	public void setCanRut(Integer canRut) {
		this.canRut = canRut;
	}
	public Character getCanRutDv() {
		return canRutDv;
	}
	public void setCanRutDv(Character canRutDv) {
		this.canRutDv = canRutDv;
	}
	public String getCanEstado() {
		return canEstado;
	}
	public void setCanEstado(String canEstado) {
		this.canEstado = canEstado;
	}
	public String getCanEstadoCandidatura() {
		return canEstadoCandidatura;
	}
	public void setCanEstadoCandidatura(String canEstadoCandidatura) {
		this.canEstadoCandidatura = canEstadoCandidatura;
	}
	public Boolean getCanEliminado() {
		return canEliminado;
	}
	public void setCanEliminado(Boolean canEliminado) {
		this.canEliminado = canEliminado;
	}
	public Date getCanCreated() {
		return canCreated;
	}
	public void setCanCreated(Date canCreated) {
		this.canCreated = canCreated;
	}
	public Date getCanModified() {
		return canModified;
	}
	public void setCanModified(Date canModified) {
		this.canModified = canModified;
	}
	public String getCanCodigoOrigen() {
		return canCodigoOrigen;
	}
	public void setCanCodigoOrigen(String canCodigoOrigen) {
		this.canCodigoOrigen = canCodigoOrigen;
	}
	public Integer getTpoCanId() {
		return tpoCanId;
	}
	public void setTpoCanId(Integer tpoCanId) {
		this.tpoCanId = tpoCanId;
	}
	public String getDesPacPacto() {
		return desPacPacto;
	}
	public void setDesPacPacto(String desPacPacto) {
		this.desPacPacto = desPacPacto;
	}
	public String getDesParPartido() {
		return desParPartido;
	}
	public void setDesParPartido(String desParPartido) {
		this.desParPartido = desParPartido;
	}
	public String getDesSpaPacto() {
		return desSpaPacto;
	}
	public void setDesSpaPacto(String desSpaPacto) {
		this.desSpaPacto = desSpaPacto;
	}
	public String getDesTpoCan() {
	    return desTpoCan;
	}
	public void setDesTpoCan(String desTpoCan) {
	    this.desTpoCan = desTpoCan;
	}
	public Integer getCanCantidadVotos() {
		return canCantidadVotos;
	}
	public void setCanCantidadVotos(Integer canCantidadVotos) {
		this.canCantidadVotos = canCantidadVotos;
	}
	public Boolean getCanHabilitado() {
		return canHabilitado;
	}
	public void setCanHabilitado(Boolean canHabilitado) {
		this.canHabilitado = canHabilitado;
	}

	public Boolean getCanElecto() {
		return canElecto;
	}
	public void setCanElecto(Boolean canElecto) {
		this.canElecto = canElecto;
	}
	public String getNombreCompleto() {
		StringBuilder nombreCompleto = new StringBuilder();
		nombreCompleto.append(StringUtils.stripToEmpty(getCanNombres())).append(" ");
		nombreCompleto.append(StringUtils.stripToEmpty(getCanAppPaterno())).append(" ");
		nombreCompleto.append(StringUtils.stripToEmpty(getCanAppMaterno()));
		
		return nombreCompleto.toString();
	}
	

}
