package cl.servel.gasto.model;
// Generated 13-09-2018 17:23:15 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FunFuncionalidad generated by hbm2java
 */
public class Funcionalidad implements java.io.Serializable {

	private Integer funId;
	private String funNombre;
	private Date created;
	private Boolean funEliminado;
	private Date modified;
	private String funCodigo;
	
	public Integer getFunId() {
		return funId;
	}

	public void setFunId(Integer funId) {
		this.funId = funId;
	}

	public String getFunNombre() {
		return funNombre;
	}

	public void setFunNombre(String funNombre) {
		this.funNombre = funNombre;
	}

	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Boolean getFunEliminado() {
		return funEliminado;
	}

	public void setFunEliminado(Boolean funEliminado) {
		this.funEliminado = funEliminado;
	}

	public Date getModified() {
		return modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}
	

//	public Set<RelPerfilFuncionalidad> getRelPerfilFuncionalidads() {
//		return relPerfilFuncionalidads;
//	}
//
//	public void setRelPerfilFuncionalidads(Set<RelPerfilFuncionalidad> relPerfilFuncionalidads) {
//		this.relPerfilFuncionalidads = relPerfilFuncionalidads;
//	}

	public String getFunCodigo() {
		return funCodigo;
	}

	public void setFunCodigo(String funCodigo) {
		this.funCodigo = funCodigo;
	}

	@Override
	public String toString() {
		return "Funcionalidad [funId=" + funId + ", funNombre=" + funNombre + ", created=" + created + ", funEliminado="
				+ funEliminado + ", modified=" + modified + "]";
	}

	

}
