package cl.servel.gasto.model;
// Generated 13-09-2018 17:23:15 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HistoricoAdmin generated by hbm2java
 */
public class HistoricoAdmin implements java.io.Serializable {

	private Integer hisId;
	private Integer admAdministradorElectoral;
	private Integer canCandidato;
	private Integer eveEventoEleccionario;
	private Integer parPartido;
	private Date hisFechaInicio;
	private Date hisFechaTermino;
	private String hisEstado;
	private Boolean hisEliminado;
	private Date hisCreated;
	private Date hisModified;
	private Date hisFechaRenuncia;
	
	
	public Integer getHisId() {
		return hisId;
	}
	public void setHisId(Integer hisId) {
		this.hisId = hisId;
	}
	public Integer getAdmAdministradorElectoral() {
		return admAdministradorElectoral;
	}
	public void setAdmAdministradorElectoral(Integer admAdministradorElectoral) {
		this.admAdministradorElectoral = admAdministradorElectoral;
	}
	public Integer getCanCandidato() {
		return canCandidato;
	}
	public void setCanCandidato(Integer canCandidato) {
		this.canCandidato = canCandidato;
	}
	public Integer getEveEventoEleccionario() {
		return eveEventoEleccionario;
	}
	public void setEveEventoEleccionario(Integer eveEventoEleccionario) {
		this.eveEventoEleccionario = eveEventoEleccionario;
	}
	public Integer getParPartido() {
		return parPartido;
	}
	public void setParPartido(Integer parPartido) {
		this.parPartido = parPartido;
	}
	public Date getHisFechaInicio() {
		return hisFechaInicio;
	}
	
	public Date getHisFechaTermino() {
		return hisFechaTermino;
	}
	public void setHisFechaTermino(Date hisFechaTermino) {
		this.hisFechaTermino = hisFechaTermino;
	}
	public void setHisFechaInicio(Date hisFechaInicio) {
		this.hisFechaInicio = hisFechaInicio;
	}
	public String getHisEstado() {
		return hisEstado;
	}
	public void setHisEstado(String hisEstado) {
		this.hisEstado = hisEstado;
	}
	public Boolean getHisEliminado() {
		return hisEliminado;
	}
	public void setHisEliminado(Boolean hisEliminado) {
		this.hisEliminado = hisEliminado;
	}
	public Date getHisCreated() {
		return hisCreated;
	}
	public void setHisCreated(Date hisCreated) {
		this.hisCreated = hisCreated;
	}
	public Date getHisModified() {
		return hisModified;
	}
	public void setHisModified(Date hisModified) {
		this.hisModified = hisModified;
	}
	
	public Date getHisFechaRenuncia() {
		return hisFechaRenuncia;
	}
	public void setHisFechaRenuncia(Date hisFechaRenuncia) {
		this.hisFechaRenuncia = hisFechaRenuncia;
	}
	
	@Override
	public String toString() {
	    return "HistoricoAdmin [hisId=" + hisId + ", admAdministradorElectoral=" + admAdministradorElectoral
		    + ", canCandidato=" + canCandidato + ", eveEventoEleccionario=" + eveEventoEleccionario
		    + ", parPartido=" + parPartido + ", hisFechaInicio=" + hisFechaInicio + ", hisEstado=" + hisEstado
		    + ", hisEliminado=" + hisEliminado + ", hisCreated=" + hisCreated + ", hisModified=" + hisModified
		    + ", hisFechaRenuncia=" + hisFechaRenuncia + "]";
	}
}
