package cl.servel.gasto.model;
// Generated 13-09-2018 17:23:15 by Hibernate Tools 5.2.11.Final

import java.util.Date;

/**
 * Parametros generated by hbm2java
 */
public class Parametros implements java.io.Serializable {

	private Integer pamId;
	private Date pamCreated;
	private Date pamModified;
	private String pamNombre;
	private String valor;
	private Boolean parametroSistema;
	private Boolean pamEliminado;
	private Integer idEventoEleccionario;
	private String pamDescripcion;
	private String pamCodTipo;
	
	public Integer getPamId() {
		return pamId;
	}
	public void setPamId(Integer pamId) {
		this.pamId = pamId;
	}
	public Date getPamCreated() {
		return pamCreated;
	}
	public void setPamCreated(Date pamCreated) {
		this.pamCreated = pamCreated;
	}
	public Date getPamModified() {
		return pamModified;
	}
	public void setPamModified(Date pamModified) {
		this.pamModified = pamModified;
	}
	public String getPamNombre() {
		return pamNombre;
	}
	public void setPamNombre(String pamNombre) {
		this.pamNombre = pamNombre;
	}
	public String getValor() {
		return valor;
	}
	public void setValor(String valor) {
		this.valor = valor;
	}
	public Boolean getParametroSistema() {
		return parametroSistema;
	}
	public void setParametroSistema(Boolean parametroSistema) {
		this.parametroSistema = parametroSistema;
	}
	public Boolean getPamEliminado() {
		return pamEliminado;
	}
	public void setPamEliminado(Boolean pamEliminado) {
		this.pamEliminado = pamEliminado;
	}
	public Integer getIdEventoEleccionario() {
		return idEventoEleccionario;
	}
	public void setIdEventoEleccionario(Integer idEventoEleccionario) {
		this.idEventoEleccionario = idEventoEleccionario;
	}
	
	public String getPamDescripcion() {
		return pamDescripcion;
	}

	public void setPamDescripcion(String pamDescripcion) {
		this.pamDescripcion = pamDescripcion;
	}

	
	public String getPamCodTipo() {
		return this.pamCodTipo;
	}

	public void setPamCodTipo(String pamCodTipo) {
		this.pamCodTipo = pamCodTipo;
	}
	@Override
	public String toString() {
		return "Parametros [pamId=" + pamId + ", pamCreated=" + pamCreated + ", pamModified=" + pamModified
				+ ", pamNombre=" + pamNombre + ", valor=" + valor + ", parametroSistema=" + parametroSistema
				+ ", pamEliminado=" + pamEliminado + ", idEventoEleccionario=" + idEventoEleccionario
				+ ", pamDescripcion=" + pamDescripcion + ", pamCodTipo=" + pamCodTipo + "]";
	}
	
}
