package cl.servel.gasto.model;
// Generated 20-09-2018 12:02:44 by Hibernate Tools 5.2.11.Final

import java.util.Date;

/**
 * RelAdminCandidato generated by hbm2java
 */
public class RelAdminCandidato implements java.io.Serializable {

	private int relAdminId;
	private int admAdministradorElectoralId;
	private int canCandidatoId;
	private int eventoId;
	
	private String relAdminEstado;
	private Date relAdminFecha;
	private Date rlcAdminFechaTermino;
	private Boolean relAdminEliminado;
	private Date adminCreated;
	private Date adminModified;

	public RelAdminCandidato() {
	}

	public RelAdminCandidato(int relAdminId, int admAdministradorElectoralId,
			int canCandidatoId) {
		this.relAdminId = relAdminId;
		this.admAdministradorElectoralId = admAdministradorElectoralId;
		this.canCandidatoId = canCandidatoId;
	}

	public RelAdminCandidato(int relAdminId, int admAdministradorElectoralId,
			int canCandidatoId, String relAdminEstado, Date relAdminFecha, Date rlcAdminFechaTermino, Boolean relAdminEliminado, Date creada, Date modificada, int eventoId) {
		
		this.relAdminId = relAdminId;
		this.admAdministradorElectoralId = admAdministradorElectoralId;
		this.canCandidatoId = canCandidatoId;
		this.relAdminEstado = relAdminEstado;
		this.relAdminFecha = relAdminFecha;
		this.rlcAdminFechaTermino = rlcAdminFechaTermino;
		this.relAdminEliminado = relAdminEliminado;
		this.adminCreated= creada;
		this.adminModified = modificada;
		this.eventoId=eventoId;
		
	}

	public int getRelAdminId() {
		return relAdminId;
	}

	public void setRelAdminId(int relAdminId) {
		this.relAdminId = relAdminId;
	}

	public int getAdmAdministradorElectoralId() {
		return admAdministradorElectoralId;
	}

	public void setAdmAdministradorElectoralId(int admAdministradorElectoralId) {
		this.admAdministradorElectoralId = admAdministradorElectoralId;
	}

	public int getCanCandidatoId() {
		return canCandidatoId;
	}

	public void setCanCandidatoId(int canCandidatoId) {
		this.canCandidatoId = canCandidatoId;
	}

	public String getRelAdminEstado() {
		return relAdminEstado;
	}

	public void setRelAdminEstado(String relAdminEstado) {
		this.relAdminEstado = relAdminEstado;
	}

	public Date getRelAdminFecha() {
		return relAdminFecha;
	}

	public void setRelAdminFecha(Date relAdminFecha) {
		this.relAdminFecha = relAdminFecha;
	}

	public Boolean getRelAdminEliminado() {
		return relAdminEliminado;
	}

	public void setRelAdminEliminado(Boolean relAdminEliminado) {
		this.relAdminEliminado = relAdminEliminado;
	}

	public Date getAdminCreated() {
		return adminCreated;
	}

	public void setAdminCreated(Date adminCreated) {
		this.adminCreated = adminCreated;
	}

	public Date getAdminModified() {
		return adminModified;
	}

	public void setAdminModified(Date adminModified) {
		this.adminModified = adminModified;
	}

	public int getEventoId() {
		return eventoId;
	}

	public void setEventoId(int eventoId) {
		this.eventoId = eventoId;
	}
	

	public Date getRlcAdminFechaTermino() {
		return rlcAdminFechaTermino;
	}

	public void setRlcAdminFechaTermino(Date rlcAdminFechaTermino) {
		this.rlcAdminFechaTermino = rlcAdminFechaTermino;
	}

	@Override
	public String toString() {
		return "RelAdminCandidato [relAdminId=" + relAdminId + ", admAdministradorElectoralId="
				+ admAdministradorElectoralId + ", canCandidatoId=" + canCandidatoId + ", relAdminEstado="
				+ relAdminEstado + ", relAdminFecha=" + relAdminFecha + ", relAdminEliminado=" + relAdminEliminado + "modificado="+adminModified + "creado="+ adminCreated+ "eventoId="+eventoId
				+ "]";
	}

	
}
