package cl.servel.gasto.model;
// Generated 13-09-2018 17:23:15 by Hibernate Tools 5.2.11.Final

/**
 * RelacionConfiguracionParametroId generated by hbm2java
 */
public class RelacionConfiguracionParametroId implements java.io.Serializable {

	private int idParametro;
	private int idConfiguracion;

	public RelacionConfiguracionParametroId() {
	}

	public RelacionConfiguracionParametroId(int idParametro, int idConfiguracion) {
		this.idParametro = idParametro;
		this.idConfiguracion = idConfiguracion;
	}

	public int getIdParametro() {
		return this.idParametro;
	}

	public void setIdParametro(int idParametro) {
		this.idParametro = idParametro;
	}

	public int getIdConfiguracion() {
		return this.idConfiguracion;
	}

	public void setIdConfiguracion(int idConfiguracion) {
		this.idConfiguracion = idConfiguracion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelacionConfiguracionParametroId))
			return false;
		RelacionConfiguracionParametroId castOther = (RelacionConfiguracionParametroId) other;

		return (this.getIdParametro() == castOther.getIdParametro())
				&& (this.getIdConfiguracion() == castOther.getIdConfiguracion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdParametro();
		result = 37 * result + this.getIdConfiguracion();
		return result;
	}

	@Override
	public String toString() {
		return "RelacionConfiguracionParametroId [idParametro=" + idParametro + ", idConfiguracion=" + idConfiguracion
				+ "]";
	}
	
	

}
