package cl.servel.gasto.model;
// Generated 13-09-2018 17:23:15 by Hibernate Tools 5.2.11.Final

/**
 * RelPerfilFuncionalidad generated by hbm2java
 */
public class RelPerfilFuncionalidad implements java.io.Serializable {

	private int id;
	private int idFuncionalidad;
	private int idperPerfil;
	private boolean eliminado;

	public RelPerfilFuncionalidad() {
	}
	
	

	public RelPerfilFuncionalidad(int id, int idFuncionalidad, int idperPerfil, boolean eliminado) {
		super();
		this.id = id;
		this.idFuncionalidad = idFuncionalidad;
		this.idperPerfil = idperPerfil;
		this.eliminado = eliminado;
	}



	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getIdFuncionalidad() {
		return idFuncionalidad;
	}

	public void setIdFuncionalidad(int idFuncionalidad) {
		this.idFuncionalidad = idFuncionalidad;
	}

	public int getIdperPerfil() {
		return idperPerfil;
	}

	public void setIdperPerfil(int idperPerfil) {
		this.idperPerfil = idperPerfil;
	}

	public boolean isEliminado() {
		return eliminado;
	}

	public void setEliminado(boolean eliminado) {
		this.eliminado = eliminado;
	}
	
	@Override
	public String toString() {
				
		StringBuilder sb = new StringBuilder();
		
		sb.append("RelPerfilFuncionalidad")
			.append( " [")
			.append("id=")
			.append(id)
			.append(", idFuncionalidad=")
			.append(idFuncionalidad)
			.append(", idperPerfil=")
			.append(idperPerfil)
			.append(", eliminado=")
			.append(eliminado)
			.append("]");
		
		return sb.toString();
	}
}