package cl.servel.gasto.model;
// Generated 13-09-2018 17:23:15 by Hibernate Tools 5.2.11.Final



/**
 * PerPerfil generated by hbm2java
 */
public class ResumenCalculos implements java.io.Serializable {

	
	private int resId;
	private int eleEleccion;
	private int nivNivel;
	private int parPartido;
	private String tpoNivel;
	private double resTotalVotos;
	private double resMontoFinanciamiento;
	private Integer eleIdAnterior;
	private Integer canIndepId;
	private boolean isPartidoNuevo;
	
	private int nivNivelAnterior;
	private int parPartidoAnterior;
	
	
	public int getResId() {
		return resId;
	}
	public void setResId(int resId) {
		this.resId = resId;
	}
	public int getEleEleccion() {
		return eleEleccion;
	}
	public void setEleEleccion(int eleEleccion) {
		this.eleEleccion = eleEleccion;
	}
	public int getNivNivel() {
		return nivNivel;
	}
	public void setNivNivel(int nivNivel) {
		this.nivNivel = nivNivel;
	}
	public int getParPartido() {
		return parPartido;
	}
	public void setParPartido(int parPartido) {
		this.parPartido = parPartido;
	}
	
	public String getTpoNivel() {
		return tpoNivel;
	}
	public void setTpoNivel(String tpoNivel) {
		this.tpoNivel = tpoNivel;
	}
	
	public double getResTotalVotos() {
		return resTotalVotos;
	}
	public void setResTotalVotos(double resTotalVotos) {
		this.resTotalVotos = resTotalVotos;
	}
	public double getResMontoFinanciamiento() {
		return resMontoFinanciamiento;
	}
	public void setResMontoFinanciamiento(double resMontoFinanciamiento) {
		this.resMontoFinanciamiento = resMontoFinanciamiento;
	}
	public Integer getEleIdAnterior() {
		return eleIdAnterior;
	}
	public void setEleIdAnterior(Integer eleIdAnterior) {
		this.eleIdAnterior = eleIdAnterior;
	}
	
	public Integer getCanIndepId() {
		return canIndepId;
	}
	public void setCanIndepId(Integer canIndepId) {
		this.canIndepId = canIndepId;
	}
	public boolean isPartidoNuevo() {
		return isPartidoNuevo;
	}
	public void setPartidoNuevo(boolean isPartidoNuevo) {
		this.isPartidoNuevo = isPartidoNuevo;
	}
	
	public int getNivNivelAnterior() {
		return nivNivelAnterior;
	}
	public void setNivNivelAnterior(int nivNivelAnterior) {
		this.nivNivelAnterior = nivNivelAnterior;
	}
	public int getParPartidoAnterior() {
		return parPartidoAnterior;
	}
	public void setParPartidoAnterior(int parPartidoAnterior) {
		this.parPartidoAnterior = parPartidoAnterior;
	}
}
