package cl.servel.gasto.model;
// Generated 13-09-2018 17:23:15 by Hibernate Tools 5.2.11.Final

/**
 * RlcRelNivelId generated by hbm2java
 */
public class RlcRelNivelId implements java.io.Serializable {

	private int rlcId;
	private String tpoNivCodigo;

	public RlcRelNivelId() {
	}

	public RlcRelNivelId(int rlcId, String tpoNivCodigo) {
		this.rlcId = rlcId;
		this.tpoNivCodigo = tpoNivCodigo;
	}

	public int getRlcId() {
		return this.rlcId;
	}

	public void setRlcId(int rlcId) {
		this.rlcId = rlcId;
	}

	public String getTpoNivCodigo() {
		return this.tpoNivCodigo;
	}

	public void setTpoNivCodigo(String tpoNivCodigo) {
		this.tpoNivCodigo = tpoNivCodigo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RlcRelNivelId))
			return false;
		RlcRelNivelId castOther = (RlcRelNivelId) other;

		return (this.getRlcId() == castOther.getRlcId()) && ((this.getTpoNivCodigo() == castOther.getTpoNivCodigo())
				|| (this.getTpoNivCodigo() != null && castOther.getTpoNivCodigo() != null
						&& this.getTpoNivCodigo().equals(castOther.getTpoNivCodigo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRlcId();
		result = 37 * result + (getTpoNivCodigo() == null ? 0 : this.getTpoNivCodigo().hashCode());
		return result;
	}

	@Override
	public String toString() {
		return "RlcRelNivelId [rlcId=" + rlcId + ", tpoNivCodigo=" + tpoNivCodigo + "]";
	}
	
	

}
