package cl.servel.gasto.model;
// Generated 13-09-2018 17:23:15 by Hibernate Tools 5.2.11.Final

import java.util.Date;


/**
 * SelSubEleccion generated by hbm2java
 */
public class SubEleccion implements java.io.Serializable {

	private Integer selId;
	private Integer idEleEleccion;
	private Integer idEveEventoEleccionario;
	private Integer idNivNivel;
	private Integer cantidadCandidatos;
	private Nivel nivel;
	private String codigoTpoNivel;
	private String selNombre;
	private String selCodigoOrigen;
	private Boolean selEliminado;
	private Date selModified;
	private Date selCreated;
	private Integer selCantidadElectores;
	
	
	public Integer getSelId() {
		return selId;
	}
	public void setSelId(Integer selId) {
		this.selId = selId;
	}
	public Integer getIdEleEleccion() {
		return idEleEleccion;
	}
	public void setIdEleEleccion(Integer idEleEleccion) {
		this.idEleEleccion = idEleEleccion;
	}
	public Integer getIdEveEventoEleccionario() {
		return idEveEventoEleccionario;
	}
	public void setIdEveEventoEleccionario(Integer idEveEventoEleccionario) {
		this.idEveEventoEleccionario = idEveEventoEleccionario;
	}
	public Integer getIdNivNivel() {
		return idNivNivel;
	}
	public void setIdNivNivel(Integer idNivNivel) {
		this.idNivNivel = idNivNivel;
	}
	public String getCodigoTpoNivel() {
		return codigoTpoNivel;
	}
	public void setCodigoTpoNivel(String codigoTpoNivel) {
		this.codigoTpoNivel = codigoTpoNivel;
	}
	public String getSelNombre() {
		return selNombre;
	}
	public void setSelNombre(String selNombre) {
		this.selNombre = selNombre;
	}
	public String getSelCodigoOrigen() {
		return selCodigoOrigen;
	}
	public void setSelCodigoOrigen(String selCodigoOrigen) {
		this.selCodigoOrigen = selCodigoOrigen;
	}
	public Boolean getSelEliminado() {
		return selEliminado;
	}
	public void setSelEliminado(Boolean selEliminado) {
		this.selEliminado = selEliminado;
	}
	public Date getSelModified() {
		return selModified;
	}
	public void setSelModified(Date selModified) {
		this.selModified = selModified;
	}
	public Date getSelCreated() {
		return selCreated;
	}
	public void setSelCreated(Date selCreated) {
		this.selCreated = selCreated;
	}
	public Integer getSelCantidadElectores() {
		return selCantidadElectores;
	}
	public void setSelCantidadElectores(Integer selCantidadElectores) {
		this.selCantidadElectores = selCantidadElectores;
	}
	public Integer getCantidadCandidatos() {
		return cantidadCandidatos;
	}
	public void setCantidadCandidatos(Integer cantidadCandidatos) {
		this.cantidadCandidatos = cantidadCandidatos;
	}
	public Nivel getNivel() {
		return nivel;
	}
	public void setNivel(Nivel nivel) {
		this.nivel = nivel;
	}
	

}
