package cl.servel.gasto.model;
// Generated 13-09-2018 17:23:15 by Hibernate Tools 5.2.11.Final

import java.util.Date;

/**
 * SpaPacto generated by hbm2java
 */
public class SubPacto implements java.io.Serializable {

	private Integer spaId;
	private Integer idEleccion;
	private Integer idPacPacto;
	private String spaNombre;
	private String spaSigla;
	private String spaCodigoOrigen;
	private Boolean spaEliminado;
	private Date created;
	private Date modified;
	
	
	public Integer getSpaId() {
		return spaId;
	}
	public void setSpaId(Integer spaId) {
		this.spaId = spaId;
	}
	public Integer getIdPacPacto() {
		return idPacPacto;
	}
	public void setIdPacPacto(Integer idPacPacto) {
		this.idPacPacto = idPacPacto;
	}
	public String getSpaNombre() {
		return spaNombre;
	}
	public void setSpaNombre(String spaNombre) {
		this.spaNombre = spaNombre;
	}
	public String getSpaSigla() {
		return spaSigla;
	}
	public void setSpaSigla(String spaSigla) {
		this.spaSigla = spaSigla;
	}
	public String getSpaCodigoOrigen() {
		return spaCodigoOrigen;
	}
	public void setSpaCodigoOrigen(String spaCodigoOrigen) {
		this.spaCodigoOrigen = spaCodigoOrigen;
	}
	public Boolean getSpaEliminado() {
		return spaEliminado;
	}
	public void setSpaEliminado(Boolean spaEliminado) {
		this.spaEliminado = spaEliminado;
	}
	public Date getCreated() {
		return created;
	}
	public void setCreated(Date created) {
		this.created = created;
	}
	public Date getModified() {
		return modified;
	}
	public void setModified(Date modified) {
		this.modified = modified;
	}
	public Integer getIdEleccion() {
		return idEleccion;
	}
	public void setIdEleccion(Integer idEleccion) {
		this.idEleccion = idEleccion;
	}
	
	
	}
